#!/usr/bin/php -q
<?php
  //
  // CARGO COGUMELO, É PRECISO FACER UNS CANTOS APAÑOS 
  //

  // Project location
  define('SITE_PATH', getcwd().'/c_app/');
  $_SERVER['HTTPS'] = false;
  $_SERVER['HTTP_HOST'] = '';
  $_SERVER['REQUEST_URI'] = 'cogumelo shell script';
  $_SERVER['REMOTE_ADDR'] = "local_shell";

  // cogumelo core Location
  set_include_path('.:'.SITE_PATH);

  require_once("conf/setup.dev.php"); 

  require_once(COGUMELO_LOCATION."/c_classes/CogumeloClass.php");
  require_once(SITE_PATH."/Cogumelo.php");

  global $_C;
  $_C =Cogumelo::get();

  //
//  CARGO MÓDULO DEVEL E O DEVELDBCONTROLLER, QUE É ONDE ESTÁN OS MÉTODOS QUE NOS INTERESAN
//
require_once(COGUMELO_LOCATION."/c_modules/devel/devel.php");
require_once(COGUMELO_LOCATION."/c_modules/devel/classes/controller/DevelDBController.php");

//
//  UTILIZO A CLASE COMO FARÍA DENDE UN VIEW NORMAL
//
$develdbcontrol = new DevelDBController();
//var_dump( $develdbcontrol->getTablesSQL() ); // este método, por exemplo, devolvenos todo o  SQL xerado para os VO's do proxecto


 
 if ($argc>1){ //parameters handler
    switch($argv[1]){

      case 'flush': // delete temporary files
	       exec('rm tmp/');
	       echo "archivos temporales borrados\n";
         break; 

      case 'createDB': // create database
          //$db = ReadStdin('Please enter the database: ', '');
          $user =  ReadStdin('Enter a user with privileges: ', '');
          //echo $db."\n";
          // Get the password
          fwrite(STDOUT, "Enter the password: ");
          $passwd = getPassword(true);
          // Output the password
          //echo "\nYour password: " . $password . "\n";
          createDB($user, $passwd);
        break; 

      case 'generateTables': // create database tables
        createTables();
        echo 'generate db tables';
        break;  

      case 'setPermissions': // create database tables
        setPermissions();
        break;    

      case 'bck': // do the backup of the given db
      	if ($argc>2)
      	  $file = $argv[2];//nome do ficheiro de bck
        else 
          $file = 'date +%Y%m%d-%H%M-'.DB_NAME.'.sql';
        doBackup(DB_NAME, $file);
        break;  

      case 'restore': // restore the backup of a given db
        if ($argc>2){
	       $bd = $argv[2];
         retoreDB($bd);
        }
        else
          echo "You must especify the database to retore\n"; 
        break;  

      default:
        echo "invalid parameter;try: 
        flush           to remove temporary files
        crete_db        to create a database
        restore_db      to restore a database\n";
        exit;     
    }//end switch 
}//end parameters handler
else{
  echo "Not enough arguments;try: 
        flush           to remove temporary files
        crete_db        to create a database
        restore_db      to restore a database\n";
}

function createDB($user, $passwd){
  $develdbcontrol = new DevelDBController($user, $passwd);
  $develdbcontrol->createSchemaDB();
}

function createTables(){
  $develdbcontrol = new DevelDBController();
  $develdbcontrol->createTables();
}

function setPermissions(){
  exec('mkdir c_app/tmp');
  exec('mkdir c_app/tmp/templates_c');
  exec('mkdir c_app/log');

  exec('sudo chown -R $USER:www-data httpdocs');
  exec('chmod -R go-rwx,g+rX httpdocs');

  exec('sudo chown -R $USER:www-data c_app');
  exec('chmod -R g-x,o-wx,g+rwX,o+rX c_app');
  exec('chmod -R gu+rwX,o+rX c_app/tmp c_app/log');

  echo "permisssions ready!\n";
}

function doBackup($BD, $file){

  echo $file;

  $DIR='/home/proxectos/backups/';
  exec('sudo mysqldump -u $USER -p$PASS '.$BD.'> $DIR/'.$file);
  exec('sudo gzip $DIR/'.$file);
  exec('chmod go-rwx $DIR/*');
  echo "your db was successfully saved";
}

/**
 * Get data from the shell.
 */
function ReadStdin($prompt, $valid_inputs, $default = '') { 
    while(!isset($input) || (is_array($valid_inputs) && !in_array($input, $valid_inputs)) || ($valid_inputs == 'is_file' && !is_file($input))) { 
        echo $prompt; 
        $input = strtolower(trim(fgets(STDIN))); 
        if(empty($input) && !empty($default)) { 
            $input = $default; 
        } 
    } 
    return $input; 
} 

/**
 * Get a password from the shell.
 * This function works on *nix systems only and requires shell_exec and stty.
 *
 * @param  boolean $stars Wether or not to output stars for given characters
 * @return string
 */
function getPassword($stars = false)
{
    // Get current style
    $oldStyle = shell_exec('stty -g');

    if ($stars === false) {
        shell_exec('stty -echo');
        $password = rtrim(fgets(STDIN), "\n");
    } else {
        shell_exec('stty -icanon -echo min 1 time 0');

        $password = '';
        while (true) {
            $char = fgetc(STDIN);

            if ($char === "\n") {
                break;
            } else if (ord($char) === 127) {
                if (strlen($password) > 0) {
                    fwrite(STDOUT, "\x08 \x08");
                    $password = substr($password, 0, -1);
                }
            } else {
                fwrite(STDOUT, "*");
                $password .= $char;
            }
        }
    }

    // Reset old style
    shell_exec('stty ' . $oldStyle);

    // Return the password
    return $password;
}

?>
