#!/usr/bin/php -q
<?php
  //
  // CARGO COGUMELO, É PRECISO FACER UNS CANTOS APAÑOS 
  //

  // Project location
  define('SITE_PATH', getcwd().'/c_app/');
  $_SERVER['HTTPS'] = false;
  $_SERVER['HTTP_HOST'] = '';
  $_SERVER['REQUEST_URI'] = 'cogumelo shell script';
  $_SERVER['REMOTE_ADDR'] = "local_shell";

  // cogumelo core Location
  set_include_path('.:'.SITE_PATH);

  require_once("conf/setup.php"); 
  

  require_once(COGUMELO_LOCATION."/c_classes/CogumeloClass.php");
  require_once(SITE_PATH."/Cogumelo.php");

  global $_C;
  $_C =Cogumelo::get();

  //
  //  CARGO MÓDULO DEVEL E O DEVELDBCONTROLLER, QUE É ONDE ESTÁN OS MÉTODOS QUE NOS INTERESAN
  //
  require_once(COGUMELO_LOCATION."/c_modules/devel/devel.php");
  require_once(COGUMELO_LOCATION."/c_modules/devel/classes/controller/DevelDBController.php");

  //
  //  UTILIZO A CLASE COMO FARÍA DENDE UN VIEW NORMAL
  //
  $develdbcontrol = new DevelDBController();
  //var_dump( $develdbcontrol->getTablesSQL() ); // este método, por exemplo, devolvenos todo o  SQL xerado para os VO's do proxecto


   if ($argc>1){ //parameters handler
      switch($argv[1]){
        case 'setPermissions': // create database tables
          setPermissions();
        break;   
        
        case 'createDB': // create database
          $user =  ReadStdin("Enter an user with privileges:\n", '');
          // Get the password
          fwrite(STDOUT, "Enter the password:\n");
          $passwd = getPassword(true);
          createDB($user, $passwd);
          fwrite(STDOUT, "\n--\n");
        break; 

        case 'createTables': // create database tables
          createTables();
          echo "\nGenerated db tables\n";
        break;    

        case 'bckDB': // do the backup of the db
          if ($argc>2){
            $file = $argv[2].'.sql';//name of the backup file
          }
          else{
            $file = false;
          }
          $user =  ReadStdin('Enter an user with privileges: ', '');
          doBackup(DB_NAME, $user, $file);
        break;  

        case 'restoreDB': // restore the backup of a given db
          if ($argc>2){
           $db = $argv[2];
           $user =  ReadStdin('Enter an user with privileges: ', '');
           retoreDB(DB_NAME, $user, $db);
          }
          else{
            echo "You must especify the database to restore\n"; 
          }
        break;  

        case 'installDependences': 
            Cogumelo::load('c_controller/DependencesController');

            $dependencesControl = new DependencesController();
            $dependencesControl->installDependences();
        break; 

        /* We will execute this two actions from web as we need to operate with the apache permissions*/
        case 'flush': // delete temporary files
           exec('sudo chown -R $USER:www-data c_app');
           exec('chmod -R gu+rwX,o+rX c_app/tmp');
           exec('rm c_app/tmp/templates_c/*');
           echo "\nTemporary files deleted!\n";
        break;    

        case 'rotateLogs': 
            rotateLogs();
        break;  

        default:
          echo "Invalid parameter;try: 
          flush                 to remove temporary files
          setPermissions        to set the folder permission
          creteDB               to create a database
          creteTables           to generate the tables
          bckDB                 to do a DB backup (optional arg: filename)
          restoreDB             to restore a database
          installDependences    to install all modules dependencies\n";

      }//end switch 
  }//end parameters handler
  else{
    echo "Not enough arguments;try: 
          flush                 to remove temporary files
          setPermissions        to set the folder permission
          creteDB               to create a database
          creteTables           to generate the tables
          bckDB                 to do a DB backup (optional arg: filename)
          restoreDB             to restore a database
          installDependences    to install all modules dependencies\n";
  }

  function createDB($user, $passwd){
    $develdbcontrol = new DevelDBController($user, $passwd);
    $develdbcontrol->createSchemaDB();
    echo "\nDatase created!\n";
  }

  function createTables(){

    Cogumelo::load('c_controller/ModuleController');
    $moduleControl = new ModuleController(false, true);

    $develdbcontrol = new DevelDBController();
    $develdbcontrol->createTables();
  }

  function setPermissions(){

    // falta comprobar se existen os directorios antes de crealos

    if (!is_dir('c_app/tmp'))
      exec('mkdir c_app/tmp');
    if (!is_dir('c_app/tmp/templates_c'))
      exec('mkdir c_app/tmp/templates_c');
    if (!is_dir('c_app/log'))
      exec('mkdir c_app/log');
    if (!is_dir('c_app/backups'))
      exec('mkdir c_app/backups');
    if (!is_dir('httpdocs/mediaCache'))
      exec('mkdir httpdocs/mediaCache');  
    
    exec('sudo chown -R $USER:www-data httpdocs');
    exec('chmod -R go-rwx,g+rX httpdocs');

    exec('sudo chown -R $USER:www-data c_app');
    exec('chmod -R g-x,o-wx,g+rwX,o+rX c_app');
    exec('chmod -R gu+rwX,o+rX c_app/tmp c_app/log httpdocs/mediaCache');
    exec('sudo chown $USER:$USER c_app/backups');
    

    echo "Permissions ready!\n";
  }

  function doBackup($BD, $user, $file){

    if (!$file)
      $file = date('Ymd-Hms').'-'.$BD.'.sql';

    $DIR = BCK;

    popen('mysqldump -u '.$user.' -p '.$BD.'> '.$DIR.'/'.$file, 'r');
    exec('sudo gzip '.$DIR.'/'.$file);
    exec('chmod go-rwx '.$DIR.'/*');
    echo "\nYour db was successfully saved!\n";
  }

  function retoreDB($BD, $user, $file){

    $DIR = BCK;

    $type = exec('file '.$DIR.$file);
    $position = strpos($type, 'gzip');
    if ($position!=false){
      popen('gunzip -c '.$DIR.$file.' | mysql -u '.$user.' -p '.$BD, 'r');
    }
    else{
      popen('mysql -u '.$user.' -p '.$BD.'< '.$DIR.$file, 'r');
    }
    echo "\nYour db was successfully restored!\n";
  }

  /**
   * Get data from the shell.
   */
  function ReadStdin($prompt, $valid_inputs, $default = '') { 
      while(!isset($input) || (is_array($valid_inputs) && !in_array($input, $valid_inputs)) || ($valid_inputs == 'is_file' && !is_file($input))) { 
          echo $prompt; 
          $input = strtolower(trim(fgets(STDIN))); 
          if(empty($input) && !empty($default)) { 
              $input = $default; 
          } 
      } 
      return $input; 
  } 

  /**
   * Get a password from the shell.
   * This function works on *nix systems only and requires shell_exec and stty.
   *
   * @param  boolean $stars Wether or not to output stars for given characters
   * @return string
   */
  function getPassword($stars = false)
  {
      // Get current style
      $oldStyle = shell_exec('stty -g');

      if ($stars === false) {
          shell_exec('stty -echo');
          $password = rtrim(fgets(STDIN), "\n");
      } else {
          shell_exec('stty -icanon -echo min 1 time 0');

          $password = '';
          while (true) {
              $char = fgetc(STDIN);

              if ($char === "\n") {
                  break;
              } else if (ord($char) === 127) {
                  if (strlen($password) > 0) {
                      fwrite(STDOUT, "\x08 \x08");
                      $password = substr($password, 0, -1);
                  }
              } else {
                  fwrite(STDOUT, "*");
                  $password .= $char;
              }
          }
      }

      // Reset old style
      shell_exec('stty ' . $oldStyle);

      // Return the password
      return $password;
  }
  
  function rotateLogs(){
    exec('gzip -c c_app/log/cogumelo.log > c_app/backups/'.date('Ymd-Hms').'-cogumelo.log.gz');
    exec('gzip -c c_app/log/cogumelo_error.log > c_app/backups/'.date('Ymd-Hms').'-cogumelo_error.log.gz');
    exec('gzip -c c_app/log/cogumelo_debug.log > c_app/backups/'.date('Ymd-Hms').'-cogumelo_debug.log.gz');
    echo "\nLogs rotated\n";
  }
  

?>
